2023-01-20T09:50:37.4065506-03:00 0HMNQSJH1CMGL:00000001 [ERR] The view '"RegisterSecretaries"' was not found. Searched locations: ["/Views/Secretaries/RegisterSecretaries.cshtml", "/Views/Shared/RegisterSecretaries.cshtml", "/Pages/Shared/RegisterSecretaries.cshtml"] (9bb2756c)
2023-01-20T09:50:37.4761580-03:00 0HMNQSJH1CMGL:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'RegisterSecretaries' was not found. The following locations were searched:
/Views/Secretaries/RegisterSecretaries.cshtml
/Views/Shared/RegisterSecretaries.cshtml
/Pages/Shared/RegisterSecretaries.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-20T09:51:14.1667708-03:00 0HMNQSJTU2VF6:00000007 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:12:00.9073258-03:00 0HMNQSTC78OFB:0000002D [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:13:01.2396792-03:00 0HMNQT01V52G1:00000013 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:13:14.5582458-03:00 0HMNQT0B2355H:00000005 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:13:14.5582457-03:00 0HMNQT0B2355H:00000003 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:13:14.6181001-03:00 0HMNQT0B2355H:00000009 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:13:36.3629851-03:00 0HMNQT0B2355J:00000001 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:15:36.9257605-03:00 0HMNQT1ACQM88:0000001F [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:21:28.5425945-03:00 0HMNQT1ACQM89:00000001 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:24:13.8821516-03:00 0HMNQT1ACQM89:00000059 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
2023-01-20T10:31:50.5558125-03:00 0HMNQTAHUFC8J:00000017 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Property 'JsonResult.SerializerSettings' must be an instance of type 'System.Text.Json.JsonSerializerOptions'.
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.GetSerializerOptions(JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-20T10:33:08.1359679-03:00 0HMNQTBB6TL35:00000019 [ERR] Erro ao Cadastrar Secretaria!An error occurred while updating the entries. See the inner exception for details. (d1156d2b)
